### ISSUE TITLE
EnvironmentError("adb is not working.")

### ISSUE THREAD

**Issue by bharath108** [xiaocong/uiautomator#101]
$ python2.7
Python 2.7.5 (default, Oct  2 2013, 22:34:09)
[GCC 4.8.1] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from uiautomator import device
>>> device(text='Run Benchmarks').click()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/uiautomator-0.1.35-py2.7.egg/uiautomator/__init__.py", line 74, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/uiautomator-0.1.35-py2.7.egg/uiautomator/__init__.py", line 843, in _click
    return self.jsonrpc.click(self.selector)
  File "/usr/lib/python2.7/site-packages/uiautomator-0.1.35-py2.7.egg/uiautomator/__init__.py", line 422, in wrapper
    server.start(timeout=30)
  File "/usr/lib/python2.7/site-packages/uiautomator-0.1.35-py2.7.egg/uiautomator/__init__.py", line 450, in start
    files = self.push()
  File "/usr/lib/python2.7/site-packages/uiautomator-0.1.35-py2.7.egg/uiautomator/__init__.py", line 391, in push
    self.adb.cmd("push", filename, "/data/local/tmp/").wait()
  File "/usr/lib/python2.7/site-packages/uiautomator-0.1.35-py2.7.egg/uiautomator/__init__.py", line 276, in cmd
    serial = self.device_serial()
  File "/usr/lib/python2.7/site-packages/uiautomator-0.1.35-py2.7.egg/uiautomator/__init__.py", line 293, in device_serial
    devices = self.devices()
  File "/usr/lib/python2.7/site-packages/uiautomator-0.1.35-py2.7.egg/uiautomator/__init__.py", line 309, in devices
    raise EnvironmentError("adb is not working.")
EnvironmentError: adb is not working.

new to github and uiautomator.. so sorry if this is not the right forum

**Comment by xiaocong** [comment]
Please help run command `adb devices` and check if you can see output like `List of devices attached`.

**Comment by bharath108** [comment]
thank you for your response.
yes, adb devices shows the device.
also followed instructions on copying bundle.jar uiautomator-stub.jar to /data/local/tmp/

**Comment by xiaocong** [comment]
Please help run below script:

```python
from uiautomator import device as d
print d.server.adb.raw_cmd("devices").communicate()
```

**Comment by bharath108** [comment]
thanks for your reply. here is the error i get:
$ python2.7
Python 2.7.5 (default, Oct  2 2013, 22:34:09)
[GCC 4.8.1] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> from uiautomator import device as d
>>> print d.server.adb.raw_cmd("devices").communicate()
('', "/bin/sh: -c: line 0: syntax error near unexpected token `('\n/bin/sh: -c: line 0: `/cygdrive/c/Program Files (x86)/Android/sdk/platform-tools/adb devices'\n")
>>> os.system("adb devices")
List of devices attached
5f944813        device

0

**Comment by bharath108** [comment]
works now. the command was very helpful. the problem was the space in adb path i think. "Program Files (x86)/"
