### ISSUE TITLE
IOError: RPC server not started! ... Again 

### ISSUE THREAD

**Issue by sush35** [xiaocong/uiautomator#140]
Hello Xiaocong,

I am getting the RPC server not started on some Ubuntu machines in my setup. Issue happens everytime I reboot the attached android device.

Following are the console logs:
$ pyton
>>> from uiautomator import device as d
>>> d.info
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py", line 584, in info
    return self.server.jsonrpc.deviceInfo()
  File "/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py", line 425, in wrapper
    server.start(timeout=30)
  File "/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py", line 481, in start
    raise IOError("RPC server not started!")
IOError: RPC server not started!

Logcat for above run gives following:
11-07 02:21:01.270  3082  3440 W ActivityManager: Unable to find instrumentation info for: ComponentInfo{com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner}

checked jars and adb forward list. Seems OK:
$ adb shell ls -l /data/local/tmp/
-rw-rw-rw- root     root       461493 2015-08-05 22:07 bundle.jar
-rw-rw-rw- root     root        34104 2015-08-05 22:07 uiautomator-stub.jar

$ adb forward --list
INMO50700009 tcp:9008 tcp:9008

But this gives error:
$ curl -d '{"jsonrpc":"2.0","method":"deviceInfo","id":1}' localhost:9008/jsonrpc/0
curl: (56) Recv failure: Connection reset by peer

no_proxy set correctly:
$ env | grep -i proxy
no_proxy=localhost,127.0.0.0/8,127.0.1.1,127.0.1.1*,local.home

Only way to start everytime is:
$adb shell uiautomator runtest bundle.jar uiautomator-stub.jar -c com.github.uiautomatorstub.Stub&
[1] 11348
$ INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.github.uiautomatorstub.Stub:
INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
INSTRUMENTATION_STATUS: test=testUIAutomatorStub
INSTRUMENTATION_STATUS: class=com.github.uiautomatorstub.Stub
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS_CODE: 1

I am not sure why in some machines I have to manually start it everytime. Affecting the automation run. 

Please help..

Thanks!

**Comment by xiaocong** [comment]
If you are using py-uiautomator v0.2+, please try to run `adb shell pm uninstall com.github.uiautomator` and `adb shell pm uninstall com.github.uiautomator.test` firstly, and then rerun your script.

**Comment by SivaKranthiKumar** [comment]
We are also facing same issue in some PCs. Same device working fine on other PCs. Need to debug it next week. I will let u know if found any solution

**Comment by sush35** [comment]
Hi,

Tried the commands, but giving errors. Please find the console logs and logcat:
ConsoleLogs:
$ adb shell pm uninstall com.github.uiautomator
Failure [DELETE_FAILED_INTERNAL_ERROR]

Logcat:
11-10 03:11:58.891 12591 12591 D AndroidRuntime: Calling main entry com.android.commands.pm.Pm
11-10 03:11:58.903  3097  3389 I PackageManager: Package doesn't exist in get block uninstall com.github.uiautomator
--------- beginning of system
11-10 03:11:58.904  3097  3122 W PackageManager: Package named 'com.github.uiautomator' doesn't exist.
11-10 03:11:58.905  3097  3122 I art     : Starting a blocking GC Explicit
11-10 03:11:58.942  3097  3122 I art     : Explicit concurrent mark sweep GC freed 73730(4MB) AllocSpace objects, 38(1548KB) LOS objects, 33% free, 17MB/25MB, paused 831us total 37.312ms
11-10 03:11:58.944 12591 12591 E Pm      : Failure details: Bundle[{android.content.pm.extra.STATUS=1, android.content.pm.extra.PACKAGE_NAME=com.github.uiautomator, android.content.pm.extra.LEGACY_STATUS=-1, android.content.pm.extra.STATUS_MESSAGE=DELETE_FAILED_INTERNAL_ERROR}]
11-10 03:11:58.946 12591 12591 I art     : System.exit called, status: 1
11-10 03:11:58.946 12591 12591 I AndroidRuntime: VM exiting with result code 1.

 
$ adb shell pm uninstall com.github.uiautomator.test
Failure [DELETE_FAILED_INTERNAL_ERROR]

Logcat:
11-10 03:12:18.709 12606 12606 D AndroidRuntime: Calling main entry com.android.commands.pm.Pm
11-10 03:12:18.718  3097  7163 I PackageManager: Package doesn't exist in get block uninstall com.github.uiautomator.test
--------- beginning of system
11-10 03:12:18.719  3097  3122 W PackageManager: Package named 'com.github.uiautomator.test' doesn't exist.
11-10 03:12:18.719  3097  3122 I art     : Starting a blocking GC Explicit
11-10 03:12:18.750  3097  3122 I art     : Explicit concurrent mark sweep GC freed 9299(736KB) AllocSpace objects, 6(220KB) LOS objects, 33% free, 17MB/25MB, paused 786us total 30.379ms
11-10 03:12:18.751 12606 12606 E Pm      : Failure details: Bundle[{android.content.pm.extra.STATUS=1, android.content.pm.extra.PACKAGE_NAME=com.github.uiautomator.test, android.content.pm.extra.LEGACY_STATUS=-1, android.content.pm.extra.STATUS_MESSAGE=DELETE_FAILED_INTERNAL_ERROR}]
11-10 03:12:18.753 12606 12606 I art     : System.exit called, status: 1
11-10 03:12:18.753 12606 12606 I AndroidRuntime: VM exiting with result code 1.

Using Uiautomator python version : 0.2.5 on Ubuntu 14.04
$ pip show uiautomator
 Name: uiautomator
Version: 0.2.5
Location: /usr/local/lib/python2.7/dist-packages
Requires:

Following are my env variable in ~/.bashrc
export no_proxy=localhost,127.0.0.0/8,127.0.1.1,127.0.1.1*,local.home
export ANDROID_HOME=$HOME/Downloads/android-sdk-linux
export PATH=$ANDROID_HOME/platform-tools:$PATH
export PATH=$ANDROID_HOME/tools:$PATH
export PATH=$ANDROID_HOME/platforms:$PATH

Thanks and Regards

**Comment by xiaocong** [comment]
@sush35 Likely the apk was not installed properly. Please check if there is any setting which may block the `adb install ...` command, or you can try to install the two apks distributed with py-uiautomator manually.

**Comment by sush35** [comment]
@xiaocong
Hi
I have already disabled "Verify apps over USB" in dev options and did "adb root" before every trial. Is there more required to ensure "adb install.." works?

Issue Resolved after mannually installing apks..
$ adb install app-uiautomator.apk
5061 KB/s (1523739 bytes in 0.293s)
	pkg: /data/local/tmp/app-uiautomator.apk
Success

$ adb install app-uiautomator-test.apk 
3657 KB/s (1239378 bytes in 0.330s)
	pkg: /data/local/tmp/app-uiautomator-test.apk
Success

Logs before installing :
>>> d.info
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py", line 584, in info
    return self.server.jsonrpc.deviceInfo()
  File "/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py", line 425, in wrapper
    server.start(timeout=30)
  File "/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py", line 481, in start
    raise IOError("RPC server not started!")
IOError: RPC server not started!

Logs after installing apks
>>> d.info
{u'displayRotation': 0, u'displaySizeDpY': 1097, u'displaySizeDpX': 686, u'screenOn': True, u'displayWidth': 1200, u'productName': u'r2_cht_hr', u'currentPackageName': u'com.android.settings', u'sdkInt': 23, u'displayHeight': 1836, u'naturalOrientation': True}
>>> 


What can be preventing the system from installing apks? Using ubuntu 14.04. Is some setting required? last time for similar issue, after updating env for no_proxy fixed it?
Not sure what is wrong this time..

Thanks,

**Comment by FaaduVineet** [comment]
Hi Xiaocong,
I am also facing the very same issue.
As you said, we need to delete our bundle.jar from /tmp/lib/...  from the computer. But i have my file in /usr/local/lib/python2.7/dist-packages/uiautomator/libs and it is with the size of 461.5kb. 
So, in this case what you suggest to do with.
For some phone, it works and for some it doesn't.

**Comment by henriquearauj** [comment]
Hi Xiaocong,

I ran the command "adb shell pm list instrumentation" on Android 7.0 and not return the UI automator Instrumentation, do you know if the uiautomator won't work on Android 7.0?

**Comment by libyoung** [comment]
405: self.adb.cmd("install", "-rt", os.path.join(base_dir, apk)).wait()
it should modify with "-r -t" instead of "-rt".
