### ISSUE TITLE
Drag operation never return.

### ISSUE THREAD

**Issue by yunfanzhang** [xiaocong/uiautomator#145]
I use dev.drag(XXXXX) when my android emulator start, But sometimes, It may be never return. 
When I use control + c kill the process
The stack is 
Traceback (most recent call last):
  File "weixin_hack_emulator_client.py", line 493, in <module>

  File "weixin_hack_emulator_client.py", line 487, in main
    if not dev:
  File "weixin_hack_emulator_client.py", line 386, in login2weixin
    def login2weixin(self):
  File "weixin_hack_emulator_client.py", line 415, in init_emulator

  File "weixin_hack_emulator_client.py", line 367, in start_emulator
    self.unlock_screen()
  File "weixin_hack_emulator_client.py", line 375, in unlock_screen
    if not self.weixin_device.dev.click(1, 1):
  File "/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py", line 598, in drag
    return self.server.jsonrpc.drag(sx, sy, ex, ey, steps)
  File "/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py", line 424, in wrapper
    server.start(timeout=30)
  File "/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py", line 469, in start
    self.install()
  File "/usr/local/lib/python2.7/dist-packages/uiautomator/__init__.py", line 404, in install
    self.adb.cmd("install", "-rt", os.path.join(base_dir, apk)).wait()
  File "/usr/lib/python2.7/subprocess.py", line 1291, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 478, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt

**Comment by masterwrw** [comment]
Whatever operation always not return when the usb line is disconnected, the program will be crash.

**Comment by xiaocong** [comment]
The error occurs at the installation of apks. I will change the installation behavior later, but could you do me a favor to upload the logcat. Thank you in advance.

**Comment by masterwrw** [comment]
No log output when the usb line disconnected, just block.
and another issues is: (ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。) when i start program of first time, second time no this error.
code:
import sys
import os
import time
import json
import codecs
import socket
import threading
import logging
import random
import subprocess
from uiautomator import Device

d = Device("3329eaf")

def test():
    print("test...")
    i = 0
    while i < 100:
        i += 1
        time.sleep(1)
        print("click...", i)
        d.click(200, 200)

def main():
    dev_info = d.info
    print(dev_info)
    width = dev_info['displayWidth']
    height = dev_info['displayHeight']

    test()
    sys.exit()

got error:
D:\Python34\python.exe E:/project/pyqt/TaskProcess/test.py
{'displayWidth': 480, 'displayRotation': 0, 'displayHeight': 854, 'screenOn': True, 'currentPackageName': 'com.android.launcher', 'naturalOrientation': True, 'productName': 'P810N30', 'displaySizeDpY': 569, 'displaySizeDpX': 320, 'sdkInt': 18}
test...
click... 1
Traceback (most recent call last):
  File "D:\Python34\lib\site-packages\urllib3\connectionpool.py", line 376, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python34\lib\site-packages\urllib3\connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "D:\Python34\lib\site-packages\urllib3\connectionpool.py", line 378, in _make_request
    httplib_response = conn.getresponse()
  File "D:\Python34\lib\http\client.py", line 1172, in getresponse
    response.begin()
  File "D:\Python34\lib\http\client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "D:\Python34\lib\http\client.py", line 313, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "D:\Python34\lib\socket.py", line 371, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

**Comment by masterwrw** [comment]
I use command(adb -s xxx logcat) get some information, may be it useful for you
--------- beginning of /dev/log/system

I/ActivityManager(  878): Process com.UCMobile (pid 24262) has died.

D/AndroidRuntime(24395): Shutting down VM

D/dalvikvm(24395): GC_CONCURRENT freed 443K, 46% free 523K/968K, paused 0ms+0ms, total 4ms

D/MainApp ( 1099): [onLowMemory] 

D/dalvikvm( 1099): GC_EXPLICIT freed 4K, 18% free 2640K/3188K, paused 1ms+2ms, total 65ms

D/UIAutomatorStub(21500): URI: /jsonrpc/0, Method: POST, Header: {content-type=application/json, remote-addr=127.0.0.1, accept-encoding=identity, host=localhost:9009, content-length=78, http-client-ip=127.0.0.1}, params, {NanoHttpd.QUERY_STRING=null}, files: {postData={"method": "ping", "id": "fb55075b731b0863564a2a32249d58f0", "jsonrpc": "2.0"}}

D/UIAutomatorStub(21500): URI: /jsonrpc/0, Method: POST, Header: {content-type=application/json, remote-addr=127.0.0.1, accept-encoding=identity, host=localhost:9009, content-length=78, http-client-ip=127.0.0.1}, params, {NanoHttpd.QUERY_STRING=null}, files: {postData={"method": "ping", "id": "243a7834b1f9b249915b4632e3e2ebc7", "jsonrpc": "2.0"}}

D/AndroidRuntime(24409): 

D/AndroidRuntime(24409): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<

D/AndroidRuntime(24409): CheckJNI is OFF

D/dalvikvm(24409): Trying to load lib libjavacore.so 0x0

D/dalvikvm(24409): Added shared lib libjavacore.so 0x0

D/UIAutomatorStub(21500): URI: /jsonrpc/0, Method: POST, Header: {content-type=application/json, remote-addr=127.0.0.1, accept-encoding=identity, host=localhost:9009, content-length=84, http-client-ip=127.0.0.1}, params, {NanoHttpd.QUERY_STRING=null}, files: {postData={"method": "deviceInfo", "id": "0d739b80f885e4362f08a1924eae27a9", "jsonrpc": "2.0"}}

D/dalvikvm(24409): Trying to load lib libnativehelper.so 0x0

D/dalvikvm(24409): Added shared lib libnativehelper.so 0x0

W/JsonRpcServer(21500): Error in JSON-RPC Service

W/JsonRpcServer(21500): java.lang.reflect.InvocationTargetException

W/JsonRpcServer(21500): 	at java.lang.reflect.Method.invokeNative(Native Method)

W/JsonRpcServer(21500): 	at java.lang.reflect.Method.invoke(Method.java:525)

W/JsonRpcServer(21500): 	at com.googlecode.jsonrpc4j.JsonRpcServer.invoke(JsonRpcServer.java:513)

W/JsonRpcServer(21500): 	at com.googlecode.jsonrpc4j.JsonRpcServer.handleObject(JsonRpcServer.java:384)

W/JsonRpcServer(21500): 	at com.googlecode.jsonrpc4j.JsonRpcServer.handleNode(JsonRpcServer.java:293)

W/JsonRpcServer(21500): 	at com.googlecode.jsonrpc4j.JsonRpcServer.handle(JsonRpcServer.java:230)

W/JsonRpcServer(21500): 	at com.github.uiautomator.stub.AutomatorHttpServer.serve(AutomatorHttpServer.java:97)

W/JsonRpcServer(21500): 	at fi.iki.elonen.NanoHTTPD.serve(NanoHTTPD.java:331)

W/JsonRpcServer(21500): 	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:953)

W/JsonRpcServer(21500): 	at fi.iki.elonen.NanoHTTPD$1$1.run(NanoHTTPD.java:208)

W/JsonRpcServer(21500): 	at java.lang.Thread.run(Thread.java:841)

W/JsonRpcServer(21500): Caused by: java.lang.IllegalStateException: UiAutomation not connected!

W/JsonRpcServer(21500): 	at android.app.UiAutomation.throwIfNotConnectedLocked(UiAutomation.java:676)

W/JsonRpcServer(21500): 	at android.app.UiAutomation.waitForIdle(UiAutomation.java:519)

W/JsonRpcServer(21500): 	at android.support.test.uiautomator.UiAutomatorBridge.waitForIdle(UiAutomatorBridge.java:112)

W/JsonRpcServer(21500): 	at android.support.test.uiautomator.UiAutomatorBridge.waitForIdle(UiAutomatorBridge.java:107)

W/JsonRpcServer(21500): 	at android.support.test.uiautomator.QueryController.getCurrentPackageName(QueryController.java:499)

W/JsonRpcServer(21500): 	at android.support.test.uiautomator.UiDevice.getCurrentPackageName(UiDevice.java:654)

W/JsonRpcServer(21500): 	at com.github.uiautomator.stub.DeviceInfo.<init>(DeviceInfo.java:51)

W/JsonRpcServer(21500): 	at com.github.uiautomator.stub.DeviceInfo.getDeviceInfo(DeviceInfo.java:44)

W/JsonRpcServer(21500): 	at com.github.uiautomator.stub.AutomatorServiceImpl.deviceInfo(AutomatorServiceImpl.java:82)

W/JsonRpcServer(21500): 	... 11 more

D/dalvikvm(21500): GC_FOR_ALLOC freed 303K, 40% free 3463K/5688K, paused 26ms, total 34ms

D/UIAutomatorStub(21500): URI: /stop, Method: GET, Header: {connection=close, user-agent=Python-urllib/3.4, remote-addr=127.0.0.1, host=localhost:9009, accept-encoding=identity, http-client-ip=127.0.0.1}, params, {NanoHttpd.QUERY_STRING=null}, files: {}

I/TestRunner(21500): finished: testUIAutomatorStub(com.github.uiautomator.stub.Stub)

I/MonitoringInstrumentation(21500): Activities that are still in CREATED to PAUSED: 0

I/TestRunner(21500): run finished: 3 tests, 0 failed, 0 ignored

D/AndroidRuntime(24409): Calling main entry com.android.commands.am.Am

D/dalvikvm(24409): Note: class Landroid/app/ActivityManagerNative; has 163 unimplemented (abstract) methods

I/ActivityManager(  878): Force stopping package com.github.uiautomator appid=10075 user=0

I/ActivityManager(  878): Killing proc 21500:com.github.uiautomator/u0a10075: force stop com.github.uiautomator

W/ActivityManager(  878): Crash of app com.github.uiautomator running instrumentation ComponentInfo{com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner}

I/ActivityManager(  878): Force stopping package com.github.uiautomator appid=10075 user=0

D/dalvikvm(24429): Late-enabling CheckJNI

I/ActivityManager(  878): Start proc com.github.uiautomator for added application com.github.uiautomator: pid=24429 uid=10075 gids={50075, 3003, 1028}

W/dalvikvm(24429): Unable to resolve superclass of Lcom/zte/ZTESecurity/ZTETelephonyMSim; (182)

W/dalvikvm(24429): Link of class 'Lcom/zte/ZTESecurity/ZTETelephonyMSim;' failed

E/dalvikvm(24429): Could not find class 'com.zte.ZTESecurity.ZTETelephonyMSim', referenced from method com.zte.ZTESecurity.ZTESecurity.getIPhoneMsim

W/dalvikvm(24429): VFY: unable to resolve new-instance 82 (Lcom/zte/ZTESecurity/ZTETelephonyMSim;) in Lcom/zte/ZTESecurity/ZTESecurity;

D/dalvikvm(24429): VFY: replacing opcode 0x22 at 0x0000

W/dalvikvm(24429): Unable to resolve superclass of Lcom/zte/ZTESecurity/ZTEPhoneSubInfoMSim; (178)

W/dalvikvm(24429): Link of class 'Lcom/zte/ZTESecurity/ZTEPhoneSubInfoMSim;' failed

E/dalvikvm(24429): Could not find class 'com.zte.ZTESecurity.ZTEPhoneSubInfoMSim', referenced from method com.zte.ZTESecurity.ZTESecurity.getIPhonesubinfoMsim

W/dalvikvm(24429): VFY: unable to resolve new-instance 76 (Lcom/zte/ZTESecurity/ZTEPhoneSubInfoMSim;) in Lcom/zte/ZTESecurity/ZTESecurity;

D/dalvikvm(24429): VFY: replacing opcode 0x22 at 0x0000

W/dalvikvm(24429): Unable to resolve superclass of Lcom/zte/ZTESecurity/ZTESmsMSim; (180)

W/dalvikvm(24429): Link of class 'Lcom/zte/ZTESecurity/ZTESmsMSim;' failed

E/dalvikvm(24429): Could not find class 'com.zte.ZTESecurity.ZTESmsMSim', referenced from method com.zte.ZTESecurity.ZTESecurity.getISmsMsim

W/dalvikvm(24429): VFY: unable to resolve new-instance 80 (Lcom/zte/ZTESecurity/ZTESmsMSim;) in Lcom/zte/ZTESecurity/ZTESecurity;

D/dalvikvm(24429): VFY: replacing opcode 0x22 at 0x0000

W/dalvikvm(24429): Unable to resolve superclass of Lcom/zte/ZTESecurity/ZTETelephonyMSim; (182)

W/dalvikvm(24429): Link of class 'Lcom/zte/ZTESecurity/ZTETelephonyMSim;' failed

D/dalvikvm(24429): DexOpt: unable to opt direct call 0x0112 at 0x02 in Lcom/zte/ZTESecurity/ZTESecurity;.getIPhoneMsim

W/dalvikvm(24429): Unable to resolve superclass of Lcom/zte/ZTESecurity/ZTEPhoneSubInfoMSim; (178)

W/dalvikvm(24429): Link of class 'Lcom/zte/ZTESecurity/ZTEPhoneSubInfoMSim;' failed

D/dalvikvm(24429): DexOpt: unable to opt direct call 0x00cf at 0x02 in Lcom/zte/ZTESecurity/ZTESecurity;.getIPhonesubinfoMsim

W/dalvikvm(24429): Unable to resolve superclass of Lcom/zte/ZTESecurity/ZTESmsMSim; (180)

W/dalvikvm(24429): Link of class 'Lcom/zte/ZTESecurity/ZTESmsMSim;' failed

D/dalvikvm(24429): DexOpt: unable to opt direct call 0x0106 at 0x02 in Lcom/zte/ZTESecurity/ZTESecurity;.getISmsMsim

I/dalvikvm(24429): Could not find method android.support.test.internal.runner.hidden.ExposedInstrumentationApi.execStartActivity, referenced from method android.support.test.runner.MonitoringInstrumentation.execStartActivity

W/dalvikvm(24429): VFY: unable to resolve virtual method 1114: Landroid/support/test/internal/runner/hidden/ExposedInstrumentationApi;.execStartActivity (Landroid/content/Context;Landroid/os/IBinder;Landroid/os/IBinder;Landroid/app/Activity;Landroid/content/Intent;I)Landroid/app/Instrumentation$ActivityResult;

D/dalvikvm(24429): VFY: replacing opcode 0x75 at 0x0024

I/MonitoringInstrumentation(24429): Instrumentation Started!

I/MonitoringInstrumentation(24429): Setting context classloader to 'dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.github.uiautomator.test-1.apk", zip file "/data/app/com.github.uiautomator-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.github.uiautomator.test-1, /data/app-lib/com.github.uiautomator-1, /vendor/lib, /system/lib]]]', Original: 'dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.github.uiautomator.test-1.apk", zip file "/data/app/com.github.uiautomator-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.github.uiautomator.test-1, /data/app-lib/com.github.uiautomator-1, /vendor/lib, /system/lib]]]'

I/TestRequestBuilder(24429): Scanning classpath to find tests in apks [/data/app/com.github.uiautomator.test-1.apk]

D/wpa_supplicant( 1012): RX ctrl_iface - hexdump(len=11): 53 49 47 4e 41 4c 5f 50 4f 4c 4c

D/wpa_supplicant( 1012): wlan0: Control interface command 'SIGNAL_POLL'

D/wpa_supplicant( 1012): nl80211: survey data missing!

D/dalvikvm(24429): GC_CONCURRENT freed 1507K, 35% free 2998K/4612K, paused 2ms+1ms, total 20ms

D/dalvikvm(24429): GC_CONCURRENT freed 1917K, 40% free 3126K/5152K, paused 2ms+1ms, total 58ms

D/dalvikvm(24429): WAIT_FOR_CONCURRENT_GC blocked 33ms

I/dalvikvm(24429): Failed resolving Lcom/googlecode/jsonrpc4j/spring/AbstractCompositeJsonServiceExporter; interface 2926 'Lorg/springframework/beans/factory/InitializingBean;'

W/dalvikvm(24429): Link of class 'Lcom/googlecode/jsonrpc4j/spring/AbstractCompositeJsonServiceExporter;' failed

E/TestLoader(24429): Could not find class: com.googlecode.jsonrpc4j.spring.AbstractCompositeJsonServiceExporter

W/dalvikvm(24429): Unable to resolve superclass of Lcom/googlecode/jsonrpc4j/spring/AbstractJsonServiceExporter; (2942)

W/dalvikvm(24429): Link of class 'Lcom/googlecode/jsonrpc4j/spring/AbstractJsonServiceExporter;' failed

E/TestLoader(24429): Could not find class: com.googlecode.jsonrpc4j.spring.AbstractJsonServiceExporter

I/dalvikvm(24429): Failed resolving Lcom/googlecode/jsonrpc4j/spring/AutoJsonRpcClientProxyCreator; interface 2929 'Lorg/springframework/beans/factory/config/BeanFactoryPostProcessor;'

W/dalvikvm(24429): Link of class 'Lcom/googlecode/jsonrpc4j/spring/AutoJsonRpcClientProxyCreator;' failed

E/TestLoader(24429): Could not find class: com.googlecode.jsonrpc4j.spring.AutoJsonRpcClientProxyCreator

I/dalvikvm(24429): Failed resolving Lcom/googlecode/jsonrpc4j/spring/AutoJsonRpcServiceExporter; interface 2929 'Lorg/springframework/beans/factory/config/BeanFactoryPostProcessor;'

W/dalvikvm(24429): Link of class 'Lcom/googlecode/jsonrpc4j/spring/AutoJsonRpcServiceExporter;' failed

E/TestLoader(24429): Could not find class: com.googlecode.jsonrpc4j.spring.AutoJsonRpcServiceExporter

W/dalvikvm(24429): Unable to resolve superclass of Lcom/googlecode/jsonrpc4j/spring/JsonProxyFactoryBean; (2943)

W/dalvikvm(24429): Link of class 'Lcom/googlecode/jsonrpc4j/spring/JsonProxyFactoryBean;' failed

E/TestLoader(24429): Could not find class: com.googlecode.jsonrpc4j.spring.JsonProxyFactoryBean

W/dalvikvm(24429): Unable to match class for part: 'Landroid/graphics/Outline;)V'

W/TestLoader(24429): java.lang.NoClassDefFoundError: android/graphics/Outline in isTestClass for android.support.v4.graphics.drawable.RoundedBitmapDrawable21

D/AndroidRuntime(24445): 

D/AndroidRuntime(24445): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<

D/AndroidRuntime(24445): CheckJNI is OFF

D/dalvikvm(24445): Trying to load lib libjavacore.so 0x0

D/dalvikvm(24445): Added shared lib libjavacore.so 0x0

D/dalvikvm(24445): Trying to load lib libnativehelper.so 0x0

D/dalvikvm(24445): Added shared lib libnativehelper.so 0x0

D/dalvikvm(24429): GC_CONCURRENT freed 1884K, 38% free 3286K/5280K, paused 2ms+2ms, total 46ms

D/dalvikvm(24429): WAIT_FOR_CONCURRENT_GC blocked 9ms

I/dalvikvm(24429): Failed resolving Lcom/googlecode/jsonrpc4j/spring/AbstractCompositeJsonServiceExporter; interface 2926 'Lorg/springframework/beans/factory/InitializingBean;'

W/dalvikvm(24429): Link of class 'Lcom/googlecode/jsonrpc4j/spring/AbstractCompositeJsonServiceExporter;' failed

W/dalvikvm(24429): Unable to resolve superclass of Lcom/googlecode/jsonrpc4j/spring/CompositeJsonServiceExporter; (2209)

W/dalvikvm(24429): Link of class 'Lcom/googlecode/jsonrpc4j/spring/CompositeJsonServiceExporter;' failed

E/TestLoader(24429): Could not find class: com.googlecode.jsonrpc4j.spring.CompositeJsonServiceExporter

I/dalvikvm(24429): Failed resolving Lcom/googlecode/jsonrpc4j/spring/AbstractCompositeJsonServiceExporter; interface 2926 'Lorg/springframework/beans/factory/InitializingBean;'

W/dalvikvm(24429): Link of class 'Lcom/googlecode/jsonrpc4j/spring/AbstractCompositeJsonServiceExporter;' failed

W/dalvikvm(24429): Unable to resolve superclass of Lcom/googlecode/jsonrpc4j/spring/CompositeJsonStreamServiceExporter; (2209)

W/dalvikvm(24429): Link of class 'Lcom/googlecode/jsonrpc4j/spring/CompositeJsonStreamServiceExporter;' failed

E/TestLoader(24429): Could not find class: com.googlecode.jsonrpc4j.spring.CompositeJsonStreamServiceExporter

W/dalvikvm(24429): Unable to resolve superclass of Lcom/googlecode/jsonrpc4j/spring/AbstractJsonServiceExporter; (2942)

W/dalvikvm(24429): Link of class 'Lcom/googlecode/jsonrpc4j/spring/AbstractJsonServiceExporter;' failed

W/dalvikvm(24429): Unable to resolve superclass of Lcom/googlecode/jsonrpc4j/spring/JsonServiceExporter; (2210)

W/dalvikvm(24429): Link of class 'Lcom/googlecode/jsonrpc4j/spring/JsonServiceExporter;' failed

E/TestLoader(24429): Could not find class: com.googlecode.jsonrpc4j.spring.JsonServiceExporter

W/dalvikvm(24429): Unable to resolve superclass of Lcom/googlecode/jsonrpc4j/spring/AbstractJsonServiceExporter; (2942)

W/dalvikvm(24429): Link of class 'Lcom/googlecode/jsonrpc4j/spring/AbstractJsonServiceExporter;' failed

W/dalvikvm(24429): Unable to resolve superclass of Lcom/googlecode/jsonrpc4j/spring/JsonStreamServiceExporter; (2210)

W/dalvikvm(24429): Link of class 'Lcom/googlecode/jsonrpc4j/spring/JsonStreamServiceExporter;' failed

E/TestLoader(24429): Could not find class: com.googlecode.jsonrpc4j.spring.JsonStreamServiceExporter

D/AndroidRuntime(24445): Calling main entry com.android.commands.pm.Pm

W/dalvikvm(24445): Unable to resolve superclass of Lcom/zte/ZTESecurity/ZTETelephonyMSim; (182)

W/dalvikvm(24445): Link of class 'Lcom/zte/ZTESecurity/ZTETelephonyMSim;' failed

E/dalvikvm(24445): Could not find class 'com.zte.ZTESecurity.ZTETelephonyMSim', referenced from method com.zte.ZTESecurity.ZTESecurity.getIPhoneMsim

W/dalvikvm(24445): VFY: unable to resolve new-instance 82 (Lcom/zte/ZTESecurity/ZTETelephonyMSim;) in Lcom/zte/ZTESecurity/ZTESecurity;

D/dalvikvm(24445): VFY: replacing opcode 0x22 at 0x0000

W/dalvikvm(24445): Unable to resolve superclass of Lcom/zte/ZTESecurity/ZTEPhoneSubInfoMSim; (178)

W/dalvikvm(24445): Link of class 'Lcom/zte/ZTESecurity/ZTEPhoneSubInfoMSim;' failed

E/dalvikvm(24445): Could not find class 'com.zte.ZTESecurity.ZTEPhoneSubInfoMSim', referenced from method com.zte.ZTESecurity.ZTESecurity.getIPhonesubinfoMsim

W/dalvikvm(24445): VFY: unable to resolve new-instance 76 (Lcom/zte/ZTESecurity/ZTEPhoneSubInfoMSim;) in Lcom/zte/ZTESecurity/ZTESecurity;

D/dalvikvm(24445): VFY: replacing opcode 0x22 at 0x0000

W/dalvikvm(24445): Unable to resolve superclass of Lcom/zte/ZTESecurity/ZTESmsMSim; (180)

W/dalvikvm(24445): Link of class 'Lcom/zte/ZTESecurity/ZTESmsMSim;' failed

E/dalvikvm(24445): Could not find class 'com.zte.ZTESecurity.ZTESmsMSim', referenced from method com.zte.ZTESecurity.ZTESecurity.getISmsMsim

W/dalvikvm(24445): VFY: unable to resolve new-instance 80 (Lcom/zte/ZTESecurity/ZTESmsMSim;) in Lcom/zte/ZTESecurity/ZTESecurity;

D/dalvikvm(24445): VFY: replacing opcode 0x22 at 0x0000

W/dalvikvm(24445): Unable to resolve superclass of Lcom/zte/ZTESecurity/ZTETelephonyMSim; (182)

W/dalvikvm(24445): Link of class 'Lcom/zte/ZTESecurity/ZTETelephonyMSim;' failed

D/dalvikvm(24445): DexOpt: unable to opt direct call 0x0112 at 0x02 in Lcom/zte/ZTESecurity/ZTESecurity;.getIPhoneMsim

W/dalvikvm(24445): Unable to resolve superclass of Lcom/zte/ZTESecurity/ZTEPhoneSubInfoMSim; (178)

W/dalvikvm(24445): Link of class 'Lcom/zte/ZTESecurity/ZTEPhoneSubInfoMSim;' failed

D/dalvikvm(24445): DexOpt: unable to opt direct call 0x00cf at 0x02 in Lcom/zte/ZTESecurity/ZTESecurity;.getIPhonesubinfoMsim

W/dalvikvm(24445): Unable to resolve superclass of Lcom/zte/ZTESecurity/ZTESmsMSim; (180)

W/dalvikvm(24445): Link of class 'Lcom/zte/ZTESecurity/ZTESmsMSim;' failed

D/dalvikvm(24445): DexOpt: unable to opt direct call 0x0106 at 0x02 in Lcom/zte/ZTESecurity/ZTESecurity;.getISmsMsim

D/AndroidRuntime(24445): Shutting down VM

D/dalvikvm(24445): GC_CONCURRENT freed 443K, 46% free 523K/968K, paused 0ms+0ms, total 3ms

D/dalvikvm(24429): GC_CONCURRENT freed 1898K, 38% free 3354K/5364K, paused 2ms+1ms, total 21ms

W/dalvikvm(24429): Unable to match class for part: 'Landroid/graphics/Outline;)V'

W/TestLoader(24429): java.lang.NoClassDefFoundError: android/graphics/Outline in isTestClass for android.support.v4.graphics.drawable.DrawableWrapperLollipop

D/TestExecutor(24429): Adding listener android.support.test.internal.runner.listener.LogRunListener

D/TestExecutor(24429): Adding listener android.support.test.internal.runner.listener.InstrumentationResultPrinter

D/TestExecutor(24429): Adding listener android.support.test.internal.runner.listener.ActivityFinisherRunListener

I/TestRunner(24429): run started: 3 tests

I/TestRunner(24429): started: testApplicationTestCaseSetUpProperly(com.github.uiautomator.ApplicationTest)

I/MonitoringInstrumentation(24429): Activities that are still in CREATED to PAUSED: 0

I/TestRunner(24429): finished: testApplicationTestCaseSetUpProperly(com.github.uiautomator.ApplicationTest)

I/MonitoringInstrumentation(24429): Activities that are still in CREATED to PAUSED: 0

I/TestRunner(24429): started: testAndroidTestCaseSetupProperly(com.github.uiautomator.ApplicationTest)

I/MonitoringInstrumentation(24429): Activities that are still in CREATED to PAUSED: 0

I/TestRunner(24429): finished: testAndroidTestCaseSetupProperly(com.github.uiautomator.ApplicationTest)

I/MonitoringInstrumentation(24429): Activities that are still in CREATED to PAUSED: 0

I/TestRunner(24429): started: testUIAutomatorStub(com.github.uiautomator.stub.Stub)

I/MonitoringInstrumentation(24429): Activities that are still in CREATED to PAUSED: 0

I/dalvikvm(24429): Could not find method android.app.UiAutomation.executeShellCommand, referenced from method android.support.test.uiautomator.UiDevice.executeShellCommand

W/dalvikvm(24429): VFY: unable to resolve virtual method 183: Landroid/app/UiAutomation;.executeShellCommand (Ljava/lang/String;)Landroid/os/ParcelFileDescriptor;

D/dalvikvm(24429): VFY: replacing opcode 0x6e at 0x0006
