### ISSUE TITLE
uiautomator.JsonRPCError when try dump the wechat UI

### ISSUE THREAD

**Issue by JunyongYao** [xiaocong/uiautomator#149]
1. Open wechat, in its conversation list   
2. run device.dump(), it has following exception info:   

Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 2358, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1778, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/weidu/PycharmProjects/CodeGuard/main.py", line 10, in <module>
    xml = d.dump()
  File "/Library/Python/2.7/site-packages/uiautomator/__init__.py", line 610, in dump
    content = self.server.jsonrpc.dumpWindowHierarchy(compressed, None)
  File "/Library/Python/2.7/site-packages/uiautomator/__init__.py", line 433, in wrapper
    return _method_obj(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/uiautomator/__init__.py", line 132, in __call__
    "%s: %s" % (jsonresult["error"]["data"]["exceptionTypeName"], jsonresult["error"]["message"])
uiautomator.JsonRPCError: JsonRPC Error code: 0, Message: java.lang.IllegalArgumentException: Illegal character (d83d)

**Comment by JunyongYao** [comment]
More info here:
The issue is introduced by emotion picture (表情包) in the UI layout.
I tried native UI Automator Viewer and it will report   
>Error while obtaining UI hierarchy XML file: com.android.ddmlib.SyncException: Remote object doesn't exist!  

I guess the encode of that emotion picture caused xml parsing error.

**Comment by JunyongYao** [comment]
Seems it is an issue of uiautomator-jsonrpc-server.  
In its implementation, it uses android uiautomator to dumpWindowHierarchy. Unfortunately, the emoji ID inside will cause xml serialization error.   
One solution provided by others is to use DOM to generate XML file.  
And Google fixed this issue in Android 4.4+ (excluded).

**Comment by JunyongYao** [comment]
For those who interested in the solution, it is https://android.googlesource.com/platform/frameworks/testing/+/2b6d1da16a4e38a9704c2c67b33aadf44a85b1d2
