### ISSUE TITLE
sometimes watcher code waiting long time

### ISSUE THREAD

**Issue by kevinjh443** [xiaocong/uiautomator#157]
Hello, Thanks for your meaningful work. And I use your project like that .

device.watcher(text=u'xxxx').click(u'xxxx')
device.watchers.run()

and some times I waiting long time(may be 1 or 2 min) have no any thing work. also the next code still not running. I guess the PRC server not response. But I don`t want to any manual intervention. 

*******
so, What`s the root issue? and how to fix it?
*******
--
Thanks

**Comment by kevinjh443** [comment]
new update:

when I debug detail, I found when the script not keep going, the adb status is running the command like this, 
"adb -s a20deca9 shell am instrument -w com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner" . 
And have no any return or response. That is the way look like stop here. because "-w" just waiting here.


at the same time, adb logcat log show error like ,

01-06 01:28:33.030  4493  4506 E TestLoader: Could not find class: com.googlecode.jsonrpc4j.spring.AbstractCompositeJsonServiceExporter
01-06 01:28:33.031  4493  4506 E TestLoader: Could not find class: com.googlecode.jsonrpc4j.spring.AbstractJsonServiceExporter
01-06 01:28:33.031  4493  4506 E TestLoader: Could not find class: com.googlecode.jsonrpc4j.spring.AutoJsonRpcClientProxyCreator
01-06 01:28:33.032  4493  4506 E TestLoader: Could not find class: com.googlecode.jsonrpc4j.spring.AutoJsonRpcServiceExporter
01-06 01:28:33.033  4493  4506 E TestLoader: Could not find class: com.googlecode.jsonrpc4j.spring.CompositeJsonServiceExporter
01-06 01:28:33.034  4493  4506 E TestLoader: Could not find class: com.googlecode.jsonrpc4j.spring.CompositeJsonStreamServiceExporter
01-06 01:28:33.034  4493  4506 E TestLoader: Could not find class: com.googlecode.jsonrpc4j.spring.JsonProxyFactoryBean
01-06 01:28:33.035  4493  4506 E TestLoader: Could not find class: com.googlecode.jsonrpc4j.spring.JsonServiceExporter
01-06 01:28:33.036  4493  4506 E TestLoader: Could not find class: com.googlecode.jsonrpc4j.spring.JsonStreamServiceExporter



But I`m sure this is not the root cause about this issue. 
what is the root cause?  any idea about this issue?


it is highly appreciate if you share some suggestions.
thanks

**Comment by kevinjh443** [comment]
I read your code, found may be have a bug here.


1, add some info in python, the log, it is always connect the device, that is the jsonrpc not responded:

it is while here in code:
        while not self.alive and timeout > 0:
            time.sleep(0.1)
            timeout -= 0.1
        if not self.alive:
            raise IOError("RPC server not started!")

the log:

ping ping ping ...
kevin - url = http://localhost:9009/jsonrpc/0
INFO:urllib3.connectionpool:Starting new HTTP connection (69): localhost
kevin - the real url = http://localhost:9009/jsonrpc/0
DEBUG:urllib3.util.retry:Incremented Retry for (url='/jsonrpc/0'): Retry(total=2, connect=None, read=None, redirect=None)
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(10054, ''))': /jsonrpc/0
INFO:urllib3.connectionpool:Starting new HTTP connection (70): localhost
DEBUG:urllib3.util.retry:Incremented Retry for (url='/jsonrpc/0'): Retry(total=1, connect=None, read=None, redirect=None)
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(10054, ''))': /jsonrpc/0
INFO:urllib3.connectionpool:Starting new HTTP connection (71): localhost
DEBUG:urllib3.util.retry:Incremented Retry for (url='/jsonrpc/0'): Retry(total=0, connect=None, read=None, redirect=None)
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(10054, ''))': /jsonrpc/0
INFO:urllib3.connectionpool:Starting new HTTP connection (72): localhost
INFO:urllib3.connectionpool:Starting new HTTP connection (73): localhost



2,  the android device error log when python try to connect device:

04-12 11:20:30.920  1785  3506 D PowerManagerService:   PARTIAL_WAKE_LOCK              '*alarm*' (uid=1000, pid=1785, ws=WorkSource{10223})
04-12 11:20:30.921  1900  1900 D ReportAlarmReceiver: action--com.hj.dictation.REPORT_ALARM
04-12 11:20:30.926  1785  1785 D PowerManagerService:   DOZE_WAKE_LOCK                 'DreamManagerService' (uid=1000, pid=1785, ws=null)
04-12 11:20:30.933  1900  1931 E AndroidRuntime: FATAL EXCEPTION: worker2
04-12 11:20:30.933  1900  1931 E AndroidRuntime: Process: com.hj.dictation, PID: 1900
04-12 11:20:30.933  1900  1931 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a
 null object reference
04-12 11:20:30.933  1900  1931 E AndroidRuntime:        at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
04-12 11:20:30.933  1900  1931 E AndroidRuntime:        at org.json.JSONTokener.nextValue(JSONTokener.java:94)
04-12 11:20:30.933  1900  1931 E AndroidRuntime:        at org.json.JSONObject.<init>(JSONObject.java:156)
04-12 11:20:30.933  1900  1931 E AndroidRuntime:        at org.json.JSONObject.<init>(JSONObject.java:173)
04-12 11:20:30.933  1900  1931 E AndroidRuntime:        at o.锞?藠(:281)
04-12 11:20:30.933  1900  1931 E AndroidRuntime:        at o.锂?藠(:251)
04-12 11:20:30.933  1900  1931 E AndroidRuntime:        at o.丞.藠(:148)
04-12 11:20:30.933  1900  1931 E AndroidRuntime:        at o.丞.藠(:50)
04-12 11:20:30.933  1900  1931 E AndroidRuntime:        at o.锂?藠(:84)
04-12 11:20:30.933  1900  1931 E AndroidRuntime:        at o.釘?藠(:52)
04-12 11:20:30.933  1900  1931 E AndroidRuntime:        at o.啶?藠(:74)
04-12 11:20:30.933  1900  1931 E AndroidRuntime:        at o.啶?run(:55)
04-12 11:20:30.935  1900  1931 E AndroidRuntime: Error reporting crash
04-12 11:20:30.935  1900  1931 E AndroidRuntime: java.lang.SecurityException: Permission Denial: requestBugReport from pid=1900, uid=10223 requires an
droid.permission.DUMP
04-12 11:20:30.935  1900  1931 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1620)
04-12 11:20:30.935  1900  1931 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1573)
04-12 11:20:30.935  1900  1931 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4454)
04-12 11:20:30.935  1900  1931 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:90)
04-12 11:20:30.935  1900  1931 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
04-12 11:20:30.935  1900  1931 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
04-12 11:20:31.705  1785  3419 W qti_sensors_hal: processTimeInd: TCT-processTimeInd Enter
04-12 11:20:31.705  1785  3419 W qti_sensors_hal: processTimeInd: TCT-processTimeInd Exit
04-12 11:20:36.612   547   639 D ThermalEngine: sensor_wait: xo_therm Wait done.




the device is android 6.0 , I think your apk `s libs code have a bug,  or your apk is not suitable for android 6.0. So , could you compile one new version of apk and jar for this project?


--
BR

**Comment by kevinjh443** [comment]
HI any update?

**Comment by neuwinker** [comment]
I have the same error as u, I guess the rps server problem like you
