### ISSUE TITLE
IOError: RPC server not started!

### ISSUE THREAD

**Issue by sunshineB** [xiaocong/uiautomator#172]
Hi :+1: 
    I am trying to run some device test using python on Ubuntu 16.04
but I am getting an error - RPC server not started! 

>>> d.info
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sdk/.local/lib/python2.7/site-packages/uiautomator/__init__.py", line 584, in info
    return self.server.jsonrpc.deviceInfo()
  File "/home/sdk/.local/lib/python2.7/site-packages/uiautomator/__init__.py", line 425, in wrapper
    server.start(timeout=30)
  File "/home/sdk/.local/lib/python2.7/site-packages/uiautomator/__init__.py", line 481, in start
    raise IOError("RPC server not started!")
IOError: RPC server not started!
 
Please tell me how to start?Thanks

**Comment by prathikshetty** [comment]
Hi ,

Please try below steps.
- adb shell pm uninstall com.github.uiautomator
- adb shell pm uninstall com.github.uiautomator.test
- adb install app-uiautomator.apk
- adb install app-uiautomator-test.apk
- adb push bundle.jar /data/local/tmp/
- adb push uiautomator-stub.jar /data/local/tmp/

And also try **print d.info** instead of d.info in python code.
Thanks

**Comment by libyoung** [comment]
405: self.adb.cmd("install", "-rt", os.path.join(base_dir, apk)).wait()
it should modify with "-r -t" instead of "-rt".

**Comment by codeskyblue** [comment]
so what is the difference?

**Comment by abhigarg** [comment]
I got an error message for the command: adb install app-uiautomator.apk
adb: error: cannot stat 'app-uiautomator.apk': No such file or directory

**Comment by SivaKranthiKumar** [comment]
@abhigarg you have to use absolute path of the apk

**Comment by didiaodanding** [comment]
执行完d.info后会导致websocket断开
 File "F:\python2.7\lib\site-packages\websocket\_core.py", line 261, in send_frame
    l = self._send(data)
  File "F:\python2.7\lib\site-packages\websocket\_core.py", line 426, in _send
    return send(self.sock, data)
  File "F:\python2.7\lib\site-packages\websocket\_socket.py", line 117, in send
    return sock.send(data)
socket.error: [Errno 10054]

**Comment by MacgradyHuang** [comment]
`
from uiautomator import Device
d = Device('014E05DE0F02000E', adb_server_host='192.168.1.68', adb_server_port=5037)
`
does above code really work? i get a "OSError: RPC server not started!". when both the adb and uiautomator are used in the same host(adb_server_host='127.0.0.1'), it works.
