### ISSUE TITLE
No activity observed while running uiatumator for android 6.0.1

### ISSUE THREAD

**Issue by prathikshetty** [xiaocong/uiautomator#175]
Hi ,

I'm trying to use Uiautomator tool using python.
I followed below steps for setting up uiautomator:

- pip install uiautomator
- Install Android SDK, and set ANDROID_HOME environment to the correct path.
- Enable ADB setting on device and connect your android device using usb with your PC.
- Allow apps to install from unknown sources on device settings.

Below is my simple python code.
```
from uiautomator import Device
d = Device('SerialNumberOfMyDevice')
d.info
```
When I run my python code in cmd prompt , I could find no activity happening.
I believe,  at least device info should be displayed.

**Kindly let me know , if I'm missing something.**

Target device : Android Version 6.0.1
Uiautomator version : 0.2.6
Windows 7 PC . 
Python version 2.7

Thanks.

**Comment by codeskyblue** [comment]
no trackback?

**Comment by prathikshetty** [comment]
Hi codeskyblue,

Since there was not activity , I had to interrupt manually (by pressing Ctrl + C in cmd line). Below is the  traceback I got.

```
Traceback (most recent call last):
  File "ui_test.py", line 4, in <module>
    d.info
  File "C:\Python27\lib\site-packages\uiautomator\__init__.py", line 584, in info
    return self.server.jsonrpc.deviceInfo()
  File "C:\Python27\lib\site-packages\uiautomator\__init__.py", line 425, in wrapper
    server.start(timeout=30)
  File "C:\Python27\lib\site-packages\uiautomator\__init__.py", line 478, in start
    time.sleep(0.1)
KeyboardInterrupt
```

Thanks

**Comment by prathikshetty** [comment]
Hi ,

The issue got solved after below steps:

- adb shell pm uninstall com.github.uiautomator
- adb shell pm uninstall com.github.uiautomator.test
- adb install app-uiautomator.apk
- adb install app-uiautomator-test.apk
- adb push bundle.jar /data/local/tmp/
- adb push uiautomator-stub.jar /data/local/tmp/
