### ISSUE TITLE
How to import Device

### ISSUE THREAD

**Issue by kimsangsoo** [xiaocong/uiautomator#192]
from uiautomator import Device

Traceback (most recent call last):
  File "/var/www/html/nspeedapp/uiautomator.py", line 9, in <module>
    from uiautomator import Device
  File "/var/www/html/nspeedapp/uiautomator.py", line 9, in <module>
    from uiautomator import Device
ImportError: cannot import name Device

what matter?????

**Comment by kimsangsoo** [comment]
python version : 2.7.5
uiautomator version : 0.2.6

**Comment by SivaKranthiKumar** [comment]
Try with small d i.e device not Device
