### ISSUE TITLE
OSSError: WinError 6 句柄无效

### ISSUE THREAD

**Issue by kingname** [xiaocong/uiautomator#213]
Everything is ok when I use macOS to run the code. But when I use windows 10, the exception alway raised when I call a element's 'exists' property.

The related code is:
` search_icon_bar = self.device(text='Show', instance=0)
        if search_icon_bar.exists:`

`Traceback (most recent call last):
  File "c:\python3\Lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\XX\ContributeSpider\Operator\UiOperator.py", line 142, in run
    self.operate_ui(start_time, task_start_time, host)
  File "C:\XX\ContributeSpider\Operator\UiOperator.py", line 175, in operate_ui
    if not self.operate_search(host):
  File "C:\XX\ContributeSpider\Operator\UiOperator.py", line 162, in operate_search
    if self.exception_revive(host):
  File "C:\XX\ContributeSpider\Operator\UiOperator.py", line 222, in exception_revive
    if self.restore_from_frontpage():
  File "C:\XX\ContributeSpider\Operator\UiOperator.py", line 296, in restore_from_frontpage
    if search_icon_bar.exists:
  File "C:\XX\venv\lib\site-packages\uiautomator\__init__.py", line 883, in exists
    return self.jsonrpc.exist(self.selector)
  File "C:\XX\venv\lib\site-packages\uiautomator\__init__.py", line 432, in wrapper
    server.start()
  File "C:\XX\venv\lib\site-packages\uiautomator\__init__.py", line 470, in start
    self.install()
  File "C:\XX\venv\lib\site-packages\uiautomator\__init__.py", line 405, in install
    self.adb.cmd("install", "-r -t", os.path.join(base_dir, apk)).wait()
  File "C:\XX\venv\lib\site-packages\uiautomator\__init__.py", line 283, in cmd
    return self.raw_cmd(*["-s", serial] + list(args))
  File "C:\XX\venv\lib\site-packages\uiautomator\__init__.py", line 292, in raw_cmd
    return subprocess.Popen(cmd_line, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "c:\python3\Lib\subprocess.py", line 594, in __init__
    _cleanup()
  File "c:\python3\Lib\subprocess.py", line 205, in _cleanup
    res = inst._internal_poll(_deadstate=sys.maxsize)
  File "c:\python3\Lib\subprocess.py", line 1025, in _internal_poll
    if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:
OSError: [WinError 6] 句柄无效。`

**Comment by yanglikai0806** [comment]
my python3.6 also meets this issue, any way to resolve this ?

**Comment by yanglikai0806** [comment]
Traceback (most recent call last):
  File "D:\Python36\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "D:\Python36\lib\site-packages\urllib3\util\connection.py", line 83, in create_connection
    raise err
  File "D:\Python36\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python36\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "D:\Python36\lib\site-packages\urllib3\connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "D:\Python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\Python36\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\Python36\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\Python36\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "D:\Python36\lib\http\client.py", line 964, in send
    self.connect()
  File "D:\Python36\lib\site-packages\urllib3\connection.py", line 166, in connect
    conn = self._new_conn()
  File "D:\Python36\lib\site-packages\urllib3\connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: : Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Jenkins\jobs\G1602A_BasicTest_001\workspace\uiautomator\__init__.py", line 429, in wrapper
    return _method_obj(*args, **kwargs)
  File "D:\Jenkins\jobs\G1602A_BasicTest_001\workspace\uiautomator\__init__.py", line 118, in __call__
    timeout=self.timeout)
  File "D:\Python36\lib\site-packages\urllib3\poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "D:\Python36\lib\site-packages\urllib3\connectionpool.py", line 678, in urlopen
    **response_kw)
  File "D:\Python36\lib\site-packages\urllib3\connectionpool.py", line 678, in urlopen
    **response_kw)
  File "D:\Python36\lib\site-packages\urllib3\connectionpool.py", line 678, in urlopen
    **response_kw)
  File "D:\Python36\lib\site-packages\urllib3\connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "D:\Python36\lib\site-packages\urllib3\util\retry.py", line 376, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9014): Max retries exceeded with url: /jsonrpc/0 (Caused by NewConnectionError(': Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Jenkins\jobs\G1602A_BasicTest_001\workspace\test\contact\test_Contact_001_004.py", line 21, in test_step
    Common(DUT).goHome()
  File "D:\Jenkins\jobs\G1602A_BasicTest_001\workspace\aw\common\__init__.py", line 235, in goHome
    d.press("home")
  File "D:\Jenkins\jobs\G1602A_BasicTest_001\workspace\uiautomator\__init__.py", line 75, in __call__
    return self.func(*args, **kwargs)
  File "D:\Jenkins\jobs\G1602A_BasicTest_001\workspace\uiautomator\__init__.py", line 810, in _press
    return self.server.jsonrpc.pressKey(str(key))
  File "D:\Jenkins\jobs\G1602A_BasicTest_001\workspace\uiautomator\__init__.py", line 432, in wrapper
    server.stop()
  File "D:\Jenkins\jobs\G1602A_BasicTest_001\workspace\uiautomator\__init__.py", line 504, in stop
    self.uninstall()
  File "D:\Jenkins\jobs\G1602A_BasicTest_001\workspace\uiautomator\__init__.py", line 413, in uninstall
    self.adb.cmd("uninstall", pkg).wait()
  File "D:\Jenkins\jobs\G1602A_BasicTest_001\workspace\uiautomator\__init__.py", line 285, in cmd
    return self.raw_cmd(*["-s", serial] + list(args))
  File "D:\Jenkins\jobs\G1602A_BasicTest_001\workspace\uiautomator\__init__.py", line 294, in raw_cmd
    return subprocess.Popen(cmd_line, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "D:\Python36\lib\subprocess.py", line 594, in __init__
    _cleanup()
  File "D:\Python36\lib\subprocess.py", line 205, in _cleanup
    res = inst._internal_poll(_deadstate=sys.maxsize)
  File "D:\Python36\lib\subprocess.py", line 1025, in _internal_poll
    if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:
OSError: [WinError 6] 句柄无效。
==================================
above is the console log
my OS is win7, python version is 3.6

**Comment by dktobeno1** [comment]
Have you resolved this?

**Comment by kingname** [comment]
no, so I use ubuntu to run my code.
