### ISSUE TITLE
Get exception on android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy already registered!

### ISSUE THREAD

**Issue by ngotam** [xiaocong/uiautomator#218]
Run uiautomator 1.0 on android device on version 6.0.1
Please let me know what could be issue and work around. Thanks.
***********************************
Get exception below:
05-22 14:49:12.050 31662 31662 D AndroidRuntime: Calling main entry com.android.commands.uiautomator.Launcher
05-22 14:49:12.050 31661 31661 D AndroidRuntime: Calling main entry com.android.commands.uiautomator.Launcher
05-22 14:49:12.085 31662 31662 D AndroidRuntime: Shutting down VM
05-22 14:49:12.090 31662 31662 E UiAutomatorTestRunner: uncaught exception
05-22 14:49:12.090 31662 31662 E UiAutomatorTestRunner: java.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@f18df39already registered!
05-22 14:49:12.090 31662 31662 E UiAutomatorTestRunner: 	at android.os.Parcel.readException(Parcel.java:1628)
05-22 14:49:12.090 31662 31662 E UiAutomatorTestRunner: 	at android.os.Parcel.readException(Parcel.java:1573)
05-22 14:49:12.090 31662 31662 E UiAutomatorTestRunner: 	at android.view.accessibility.IAccessibilityManager$Stub$Proxy.registerUiTestAutomationService(IAccessibilityManager.java:595)
05-22 14:49:12.090 31662 31662 E UiAutomatorTestRunner: 	at android.app.UiAutomationConnection.registerUiTestAutomationServiceLocked(UiAutomationConnection.java:337)
05-22 14:49:12.090 31662 31662 E UiAutomatorTestRunner: 	at android.app.UiAutomationConnection.connect(UiAutomationConnection.java:89)
05-22 14:49:12.090 31662 31662 E UiAutomatorTestRunner: 	at android.app.UiAutomation.connect(UiAutomation.java:197)
05-22 14:49:12.090 31662 31662 E UiAutomatorTestRunner: 	at com.android.uiautomator.core.UiAutomationShellWrapper.connect(UiAutomationShellWrapper.java:32)
05-22 14:49:12.090 31662 31662 E UiAutomatorTestRunner: 	at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAutomatorTestRunner.java:118)
05-22 14:49:12.090 31662 31662 E UiAutomatorTestRunner: 	at com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutomatorTestRunner.java:96)
05-22 14:49:12.090 31662 31662 E UiAutomatorTestRunner: 	at com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.java:91)
05-22 14:49:12.090 31662 31662 E UiAutomatorTestRunner: 	at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)
05-22 14:49:12.090 31662 31662 E UiAutomatorTestRunner: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
05-22 14:49:12.090 31662 31662 E UiAutomatorTestRunner: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:257)
05-22 14:49:12.090 31662 31662 I art     : System.exit called, status: -1

**Comment by Nikitae57** [comment]
Bump after 5 years
