### ISSUE TITLE
dump failing due to Illegal character

### ISSUE THREAD

**Issue by pedia** [xiaocong/uiautomator#231]
Same as #129, with adb logcat:

> W/JsonRpcServer(27614): Error in JSON-RPC Service
> W/JsonRpcServer(27614): java.lang.reflect.InvocationTargetException
> W/JsonRpcServer(27614): at java.lang.reflect.Method.invokeNative(Native Method)
> W/JsonRpcServer(27614): at java.lang.reflect.Method.invoke(Method.java:515)
> 
> ...
> 
> W/JsonRpcServer(27614): at android.support.test.uiautomator.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:84)
> W/JsonRpcServer(27614): at android.support.test.uiautomator.AccessibilityNodeInfoDumper.dumpWindowHierarchy(AccessibilityNodeInfoDumper.java:49)
> W/JsonRpcServer(27614): at android.support.test.uiautomator.UiDevice.dumpWindowHierarchy(UiDevice.java:946)
> W/JsonRpcServer(27614): at com.github.uiautomator.stub.AutomatorServiceImpl.dumpWindowHierarchy(AutomatorServiceImpl.java:178)
> W/JsonRpcServer(27614): at com.github.uiautomator.stub.AutomatorServiceImpl.dumpWindowHierarchy(AutomatorServiceImpl.java:164)
> W/JsonRpcServer(27614): ... 11 more
>

**Comment by pedia** [comment]
Emoji text cause it. Crashed in 

> private static void dumpNodeRec(AccessibilityNodeInfo node, XmlSerializer serializer,int index,
>             int width, int height) throws IOException {
>         serializer.startTag("", "node");
>         if (!nafExcludedClass(node) && !nafCheck(node))
>             serializer.attribute("", "NAF", Boolean.toString(true));
>         serializer.attribute("", "index", Integer.toString(index));
>         **serializer.attribute**("", "text", safeCharSeqToString(node.getText()));
>         serializer.attribute("", "resource-id", safeCharSeqToString(node.getViewIdResourceName()));
>         serializer.attribute("", "class", safeCharSeqToString(node.getClassName()));
>     

How to resolve this?
