### ISSUE TITLE
 uiAutomator 出现 ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。怎么解决的

### ISSUE THREAD

**Issue by jamesding** [xiaocong/uiautomator#246]
![image](https://user-images.githubusercontent.com/1769770/34432537-25290b2c-ecb3-11e7-91d4-9e945b796a00.png)
这是为什么啊,

**Comment by jamesding** [comment]
Traceback (most recent call last):
  File "F:\ProgramFiles\python\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "F:\ProgramFiles\python\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "F:\ProgramFiles\python\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "F:\ProgramFiles\python\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "F:\ProgramFiles\python\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "F:\ProgramFiles\python\lib\http\client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\ProgramFiles\python\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "F:\ProgramFiles\python\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "F:\ProgramFiles\python\lib\site-packages\urllib3\util\retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "F:\ProgramFiles\python\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "F:\ProgramFiles\python\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "F:\ProgramFiles\python\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "F:\ProgramFiles\python\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "F:\ProgramFiles\python\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "F:\ProgramFiles\python\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "F:\ProgramFiles\python\lib\http\client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:/jekou/demo4/ycheApp.py", line 294, in <module>
    runTask()
  File "G:/jekou/demo4/ycheApp.py", line 259, in runTask
    appStart()
  File "G:/jekou/demo4/ycheApp.py", line 253, in appStart
    d.press.home()
  File "F:\ProgramFiles\python\lib\site-packages\uiautomator\__init__.py", line 149, in __call__
    return self.func(*args, **kwargs)
  File "F:\ProgramFiles\python\lib\site-packages\uiautomator\__init__.py", line 825, in _press
    return self.server.jsonrpc.pressKey(str(key))
  File "F:\ProgramFiles\python\lib\site-packages\uiautomator\__init__.py", line 429, in wrapper
    return _JsonRPCMethod(url, method, timeout, False)(*args, **kwargs)
  File "F:\ProgramFiles\python\lib\site-packages\uiautomator\__init__.py", line 423, in wrapper
    return _method_obj(*args, **kwargs)
  File "F:\ProgramFiles\python\lib\site-packages\uiautomator\__init__.py", line 196, in __call__
    return self.remote_call(data)
  File "F:\ProgramFiles\python\lib\site-packages\uiautomator\__init__.py", line 174, in remote_call
    data=json.dumps(data).encode('utf-8'))
  File "F:\ProgramFiles\python\lib\site-packages\requests\sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "F:\ProgramFiles\python\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "F:\ProgramFiles\python\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "F:\ProgramFiles\python\lib\site-packages\requests\adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

**说是有During handling of the above exception, another exception occurred:
**

**Comment by becomemoreandmorepowerful** [comment]
有解决吗，我也遇到同样的问题。你也是在做安卓自动化测试的吗，你有比较全面的安卓功能测试用例吗。

**Comment by Earthwater** [comment]
got same error but with

**Comment by Earthwater** [comment]
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020E590D8A58>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /jsonrpc/0

i have accounted with similar error, it might be port corruption with some connection already established, but still, i am not able to locate source of this error

**Comment by listen-man** [comment]
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E0A4944940>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /jsonrpc/0
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E0A49C38E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /jsonrpc/0
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E0A49C3CD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /jsonrpc/0
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E0A49ABBB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /jsonrpc/0
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E0A49D71F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /jsonrpc/0
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E0A4944070>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /jsonrpc/0
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E0A49AB100>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /jsonrpc/0
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E0A49C3820>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /jsonrpc/0
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E0A4933490>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /jsonrpc/0




我因为遇到这种问题，捕捉不到异常，只做连接Device("10.0.0.9:5555")也会报错，不知道怎么解决，我把uiautomator安装包手动安装启动后，仍然会出现，有没有哪位大佬已经解决了的？
