### ISSUE TITLE
How to verify Uiobject status having which color green or black

### ISSUE THREAD

**Issue by Nagesh1504** [xiaocong/uiautomator#276]
Hi,

i am doing automation testing on android device, which has gear bar indicator.
This indicator will provide two colors i.e black and green so here my question is that how i can check this indicator status information and its color using uiautomator using python code?
After finding which color it is, then using this color i have to compare it weather its "Green" or "Black".?

So please help me on this one @mingyuan-xia @xiaocong @hongbinbao @jjqq2013 @xiscoxu 

Thanks in advance.

**Comment by Nagesh1504** [comment]
please help me on above requirement.
Thanks in advance:)

**Comment by iaroslavpavlynskyi** [comment]
@Nagesh1504, hello man. I have not found any possible solutions to do it using UiObject.
But maybe it will be useful for you: You can make a screenshot and process it through a pythont script using the PIL library, that can help you to get the color of a specific pixel. Maybe it's a hard way, but I think it's a possible solution.

**Comment by Nagesh1504** [comment]
Hi @iaroslavpavlynskyi  thanks for the information,

i will try with above steps :)

**Comment by Nagesh1504** [comment]
Hi @iaroslavpavlynskyi  could please tel me how i can take screenshot of below highlighted image.
![Screenshot_Particular_Area](https://user-images.githubusercontent.com/48903263/56557066-5de1a400-65b7-11e9-831c-393f7efe68a5.jpg)

Since i am able to follow above steps mentioned by you but i need specific area to be captured as showing in the above picture.
could please help me on this one :)
thanks in advance!

**Comment by SivaKranthiKumar** [comment]
You can get that object bounds from UI object use same to extract it from the screenshot

**Comment by Nagesh1504** [comment]
Hi @SivaKranthiKumar,

Could please give me an example for the above inputs provided by you, that could be help me a lot. Since i am new to this Uiautomator viwer.
thanks in advance:)

**Comment by Nagesh1504** [comment]
Hi @SivaKranthiKumar,

Any help on above request!

**Comment by iaroslavpavlynskyi** [comment]
@Nagesh1504 , hello. 
I think this comment should help you.
```python
def get_center(self, resource_id):
    ui_element = self.dev(resourceId=resource_id)
    if ui_element.exists:
        bounds = ui_element.info.get("visibleBounds") or ui_element.info.get("bounds")
        x = (bounds["left"] + bounds["right"]) / 2
        y = (bounds["top"] + bounds["bottom"]) / 2
        return (x, y)
    return False
```

The example code gets the center position of the UI element based on its resource ID, but you can change it however way that fits your needs.

_Originally posted by @ionestel in https://github.com/xiaocong/uiautomator/issues/278#issuecomment-490181469_

**Comment by Nagesh1504** [comment]
@iaroslavpavlynskyi , Hello.
The above code i have used but i am getting error as mentioned below,
Traceback (most recent call last):
  File "C:\Python27\adb.py", line 11, in <module>
    print get_center(d,"Chrome")
  File "C:\Python27\adb.py", line 3, in get_center
    ui_element = self.dev(text= text_1)
  File "C:\Python27\lib\site-packages\uiautomator\__init__.py", line 606, in __getattr__
    raise AttributeError("%s attribute not found!" % attr)
AttributeError: dev attribute not found!

May be we not able to define what is 'dev' here?

Could please help me on this one

**Comment by Nagesh1504** [comment]
@iaroslavpavlynskyi Hello,

Thanks for the help :)
I got the solution for above error and i have modified code as well as per code required for the automation.
