### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by AllenLuosong** [xiaocong/uiautomator#291]
uiautomator中判断屏幕是否锁屏时，执行如下判断报错，哪位大神帮忙看下是什么问题呀？
逻辑判断
if not d.screenOn:
    d.unlock()
报错如下
Traceback (most recent call last):
  File "D:\Program Files\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "D:\Program Files\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:/Program Files/JetBrains/app_project/mainTest.py", line 132, in check_screen
    if d.screen == "off":
  File "D:\Program Files\Python\Python37\lib\site-packages\uiautomator2\__init__.py", line 1405, in __getattr__
    return getattr(self._default_session, attr)
  File "D:\Program Files\Python\Python37\lib\site-packages\uiautomator2\session.py", line 674, in __getattr__
    if hasattr(self.server, key):
  File "D:\Program Files\Python\Python37\lib\site-packages\uiautomator2\__init__.py", line 1405, in __getattr__
    return getattr(self._default_session, attr)
  File "D:\Program Files\Python\Python37\lib\site-packages\uiautomator2\session.py", line 674, in __getattr__
    if hasattr(self.server, key):
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by taofei** [comment]
换个角度，测试机器全部保证屏幕常亮不关闭不就可以。
