### ISSUE TITLE
I can see '/u200e' being added to the beginning and the end of the text I am looking for using textMatches .

### ISSUE THREAD

**Issue by ancan-netizen** [xiaocong/uiautomator#294]

**Comment by ancan-netizen** [comment]
I want to connect to a bluetooth device, there are 2 devices with similar name. The names are **abc123** and **deabc123**. I would like to connect with **abc123**, so I would like to give **textMatches** to **abc123**, if I do so I get the bellow error 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Desktop\handset\uiautomator\__init__.py", line 80, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\Desktop\handset\uiautomator\__init__.py", line 883, in _click
    return self.jsonrpc.click(self.selector)
  File "C:\Users\Desktop\handset\uiautomator\__init__.py", line 355, in wrapper
    return _method_obj(*args, **kwargs)
  File "C:\Users\Desktop\handset\uiautomator\__init__.py", line 140, in __call__
    "%s: %s" % (jsonresult["error"]["data"], jsonresult["error"]["message"])
**uiautomator.JsonRPCError: JsonRPC Error code: -32002, Message: {'exceptionTypeName': 'android.support.test.uiautomator.UiObjectNotFoundException', 'message': 'UiSelector[CLASS=android.widget.TextView, TEXT_REGEX=abc123, RESOURCE_ID=android:id/title]'}: UiSelector[CLASS=android.widget.TextView, TEXT_REGEX=abc123, RESOURCE_ID=android:id/title]**

and if I use **textContains** it matches with the device which appears first on the page, so sometimes with **abc123** and other times with **deabc123**

Kindly help with this. Thanking in advance

**Comment by hongbinbao** [comment]
what's your android SDK version?
