### ISSUE TITLE
Double and Triple Click / Tap ?!

### ISSUE THREAD

**Issue by gokulakv** [xiaocong/uiautomator#53]
There is no functionality for Double and Triple Click / Tap, its simple to change in server rite
Please change and let me know your repo client uiautomator.py 
So that I can use it

**Comment by yeshwanth24** [comment]
Hey, Do we have to import anything? because I see that the Configurator class is not detected.

**Comment by xiaocong** [comment]
@yeshwanth24,

Please make sure:
1. Install py-uiautomator using `pip install uiautomator`. It will install the jsonrpc jar files with py-uiautomator package.
2. Do not launch jsonrpc server by yourself. py-uiautomator will launch correct jsonrpc server for you. 

If you meet the issue again, please help upload the logcat when you are running the script, else I could not help you on this.

**Comment by sudhuhegde** [comment]
Hi @xiaocong  

My double tap is not working , below code I am using for it. It always does the single click.

 config = d.server.jsonrpc.getConfigurator()
    config['actionAcknowledgmentTimeout'] = 40
    d.server.jsonrpc.setConfigurator(config)
    d(ELEMENT).click()
    d(ELEMENT).click()
    config['actionAcknowledgmentTimeout'] = 3000
    d.server.jsonrpc.setConfigurator(config)

**Comment by yanglikai0806** [comment]
Hi @xiaocong @sudhuhegde 
it is working , i add xiaocong 's code to uiautomator.py as:
`  def double_click(self, x=500, y=500):
  # set ack timeout
        config = self.server.jsonrpc.getConfigurator()
        config['actionAcknowledgmentTimeout'] = 40
        self.server.jsonrpc.setConfigurator(config)
      # double click
        self.click(x, y)
        self.click(x, y)
#         self(*args, **kwargs).click()
#         self(*args, **kwargs).click()
      # restore previous config
        config['actionAcknowledgmentTimeout'] = 3000
        self.server.jsonrpc.setConfigurator(config)`
then, it worked very well.

**Comment by yanglikai0806** [comment]
Hi @xiaocong @sudhuhegde
it is working , i add xiaocong 's code( just changed a little) to uiautomator.py as:
_______________________________________________________________
def double_click(self, x=500, y=500): 
    config = self.server.jsonrpc.getConfigurator()
    config['actionAcknowledgmentTimeout'] = 40 
    self.server.jsonrpc.setConfigurator(config) 
    self.click(x, y)
    self.click(x, y) 
    config['actionAcknowledgmentTimeout'] = 3000 
    self.server.jsonrpc.setConfigurator(config)
_______________________________________________________________
then, it worked very well.

**Comment by yemengsky** [comment]
```
for i in xrange(1,3):
	    d.click()
    	   sleep(0.01)
```
This works for me. You should sleep a while after click the view .
@yanglikai0806 @yeshwanth24

**Comment by ananthandivya** [comment]
Hi @xiaocong

I tried running your code 

   def double_click(*args, **kwargs):
        # set ack timeout
        config = d.server.jsonrpc.getConfigurator()
        config['actionAcknowledgmentTimeout'] = 40
        d.server.jsonrpc.setConfigurator(config)
        # double click
        d(*args, **kwargs).click()
        d(*args, **kwargs).click()
        # restore previous config
        config['actionAcknowledgmentTimeout'] = 3000
        d.server.jsonrpc.setConfigurator(config)
#calling the function

double_click(resourceId="com.amazon.photos:id/photo_view")

But i am getting an error as 

Traceback (most recent call last):
  File "C:/Users/dikaushi/PycharmProjects/Amozon_Pheripharals_Automation0.1/Module_TestScripts/TestScripts.py", line 133, in <module>
    main()
  File "C:/Users/dikaushi/PycharmProjects/Amozon_Pheripharals_Automation0.1/Module_TestScripts/TestScripts.py", line 130, in main
    TS.TS004_SwipeSpeeds()
  File "C:/Users/dikaushi/PycharmProjects/Amozon_Pheripharals_Automation0.1/Module_TestScripts/TestScripts.py", line 125, in TS004_SwipeSpeeds
    obj.double_click()
  File "C:\Users\dikaushi\PycharmProjects\Amozon_Pheripharals_Automation0.1\CommonLib\UIAKeywords.py", line 277, in double_click
    config = self.server.jsonrpc.getConfigurator()
AttributeError: UIAKeywords instance has no attribute 'server'

Process finished with exit code 1

Could you tell me what is this issue

**Comment by SivaKranthiKumar** [comment]
@ananthandivya You need to use device instance. Instead of `config = _self_.server.jsonrpc.getConfigurator() `use `config = **d**.server.jsonrpc.getConfigurator()`
