### ISSUE TITLE
JsonRPCError: JsonRPC Error code: -32002, Message: UiSelector[TEXT=Phone]

### ISSUE THREAD

**Issue by henrydeng** [xiaocong/uiautomator#60]
when  I run this "d2(text="Phone").click() " to click the Phone icon in idle. it can launch the dial pad. but after the end of the script ,below exception throw

```
d2(text="Phone").click()
```

  File "C:\Python27\lib\site-packages\uiautomator-0.1.32-py2.7.egg\uiautomator__init__.py", line 79, in **call**
    return self.func(_args, *_kwargs)
  File "C:\Python27\lib\site-packages\uiautomator-0.1.32-py2.7.egg\uiautomator__init__.py", line 1090, in _click
    return self.jsonrpc.click(self.selector)
  File "C:\Python27\lib\site-packages\uiautomator-0.1.32-py2.7.egg\uiautomator__init__.py", line 445, in wrapper
    return _method_obj(_args, *_kwargs)
  File "C:\Python27\lib\site-packages\uiautomator-0.1.32-py2.7.egg\uiautomator__init__.py", line 131, in **call**
    raise JsonRPCError(jsonresult["error"]["code"], jsonresult["error"]["message"])
JsonRPCError: JsonRPC Error code: -32002, Message: UiSelector[TEXT=Phone]

**Comment by hao1032** [comment]
@xiaocong 我也遇到的类型的问题，发现遇到这样的问题后，脚本已经报错停止了。但是在命令行里面执行：adb shell uiautomator runtest  uiautomator-stub.jar bundle.jar -c com.github.uiautomatorstub.Stub  
会出错，提示java.net.BindException: bind failed: EADDRINUSE (Address already in use)，是否和这个有关呢？

完整的adb错误提示：
C:\Users\xxx\Desktop>adb shell uiautomator runtest  uiautomator-stub.jar bundle.jar -c com.github.uiautomatorstub.
Stub
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
INSTRUMENTATION_STATUS: class=com.github.uiautomatorstub.Stub
INSTRUMENTATION_STATUS: stream=
com.github.uiautomatorstub.Stub:
INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: test=testUIAutomatorStub
INSTRUMENTATION_STATUS_CODE: 1
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
INSTRUMENTATION_STATUS: class=com.github.uiautomatorstub.Stub
INSTRUMENTATION_STATUS: stream=
Error in testUIAutomatorStub:
java.net.BindException: bind failed: EADDRINUSE (Address already in use)
        at libcore.io.IoBridge.bind(IoBridge.java:89)
        at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150)
        at java.net.ServerSocket.bind(ServerSocket.java:318)
        at java.net.ServerSocket.bind(ServerSocket.java:281)
        at fi.iki.elonen.NanoHTTPD.start(NanoHTTPD.java:155)
        at com.github.uiautomatorstub.Stub.setUp(Stub.java:27)
        at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAutomatorTestRunner.java:144)
        at com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutomatorTestRunner.java:87)
        at com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.java:90)
        at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:243)
        at dalvik.system.NativeStart.main(Native Method)
Caused by: libcore.io.ErrnoException: bind failed: EADDRINUSE (Address already in use)
        at libcore.io.Posix.bind(Native Method)
        at libcore.io.ForwardingOs.bind(ForwardingOs.java:40)
        at libcore.io.IoBridge.bind(IoBridge.java:87)
        ... 17 more

INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stack=java.net.BindException: bind failed: EADDRINUSE (Address already in use)
        at libcore.io.IoBridge.bind(IoBridge.java:89)
        at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150)
        at java.net.ServerSocket.bind(ServerSocket.java:318)
        at java.net.ServerSocket.bind(ServerSocket.java:281)
        at fi.iki.elonen.NanoHTTPD.start(NanoHTTPD.java:155)
        at com.github.uiautomatorstub.Stub.setUp(Stub.java:27)
        at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAutomatorTestRunner.java:144)
        at com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutomatorTestRunner.java:87)
        at com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.java:90)
        at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:243)
        at dalvik.system.NativeStart.main(Native Method)
Caused by: libcore.io.ErrnoException: bind failed: EADDRINUSE (Address already in use)
        at libcore.io.Posix.bind(Native Method)
        at libcore.io.ForwardingOs.bind(ForwardingOs.java:40)
        at libcore.io.IoBridge.bind(IoBridge.java:87)
        ... 17 more

INSTRUMENTATION_STATUS: test=testUIAutomatorStub
INSTRUMENTATION_STATUS_CODE: -1
INSTRUMENTATION_STATUS: stream=
Test results for WatcherResultPrinter=.E
Time: 0.061

FAILURES!!!
Tests run: 1,  Failures: 0,  Errors: 1


INSTRUMENTATION_STATUS_CODE: -1

C:\Users\xxx\Desktop>

**Comment by leaphan** [comment]
@cocoon-project hi,Have you resolved the problem? i met the same question and i don't know how to resolve it

**Comment by barneywilliams** [comment]
I have run into this issue intermittently as well, where a UI element is indeed on the screen, but the find fails.

**Comment by leaphan** [comment]
@barneywilliams  i can find the UI element,but  can not click it

**Comment by AfreenShaha** [comment]
Any update on this issue? Facing similar issue with Android N

**Comment by Joycetcl** [comment]
Any update on this issue? Facing similar issue with Android O
