### ISSUE TITLE
IOError: RPC server not started

### ISSUE THREAD

**Issue by zengxiucheng** [xiaocong/uiautomator#64]
> > > from uiautomator import device as d
> > > d.info

Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    d.info
  File "C:\Python27\lib\site-packages\uiautomator__init__.py", line 519, in info
    return self.server.jsonrpc.deviceInfo()
  File "C:\Python27\lib\site-packages\uiautomator__init__.py", line 400, in wrapper
    server.start()
  File "C:\Python27\lib\site-packages\uiautomator__init__.py", line 440, in start
    raise IOError("RPC server not started!")
IOError: RPC server not started!

**Comment by gokulakrishnan** [comment]
Can somebody translate the whole conversation?

**Comment by xiaocong** [comment]
> curl -d '{"jsonrpc":"2.0","method":"deviceInfo","id":1}' localhost:9008/jsonrpc/0
> 
> {"jsonrpc":"jsonrpc","id":"null","error":{"code":-32700,"message":"Parse error"}}

@gokulakrishnan, did you meet the same issue as mentioned? If yes, could you please tell me which Android device r u using?

**Comment by gokulakrishnan** [comment]
Hey Sorry for late update, I got this error resolved. I was changing the init.py code, then while debugging I got it resolved with my own changes of logging
Thanks, your code is clear

**Comment by gokulakv** [comment]
I'm using fire tablet...

On Jan 22, 2015 6:02 PM, =?UTF-8?B?6LS65pmT6IGq?= <notifications@github.com> wrote:

curl -d '{"jsonrpc":"2.0","method":"deviceInfo","id":1}' localhost:9008/jsonrpc/0

{"jsonrpc":"jsonrpc","id":"null","error":{"code":-32700,"message":"Parse error"}}

@gokulakrishnan<https://github.com/gokulakrishnan>, did you meet the same issue as mentioned? If yes, could you please tell me which Android device r u using?

**Comment by princemoseslive** [comment]
Hi All !!

I am getting this error when i run it in my L os device caught <type 'exceptions.IOError'>: RPC server not started!

Can someone help me resolve it !!

**Comment by xiaocong** [comment]
Please upload the adb logcat.

**Comment by princemoseslive** [comment]
Hi ,

Do find the log snippets:

I/Vold    (  157): Vold 2.1 (the revenge) firing up

D/Vold    (  157): Volume usbotg state changing -1 (Initializing) -> 0 (No-Media)

D/VendorConfHelper(  214): Properties $VENDOR_GROUP_LIST="AmazonPackageManager:AmazonWifiManager:CRLSetManager:AmazonDownloadManager:AmazonInputManager:AmazonLibrary:AmazonWindowManager:Chronos:ContentSupportManager:DeviceInfo:IDME:Nitro:SearchManager:SoftkeyBar:TimeService:FileLinker:AmazonActivityManager:SmartSuspend:Marketplace:AmazonKeyguardManager". processing these as possible system services.

D/VendorConfHelper(  214): Properties $VENDOR_SERVICE_MANAGER="null"  namespace ="AmazonPackageManager"

D/VendorConfHelper(  214): Properties $VENDOR_SERVICE_MANAGER="com.amazon.android.service.AmazonWifiManager"  namespace ="AmazonWifiManager"

D/VendorConfHelper(  214): Properties $VENDOR_SERVICE_MANAGER="com.amazon.android.crl.CRLsetManager"  namespace ="CRLSetManager"

D/VendorConfHelper(  214): Properties $VENDOR_SERVICE_MANAGER="com.amazon.android.app.AmazonDownloadManager"  namespace ="AmazonDownloadManager"

D/VendorConfHelper(  214): Properties $VENDOR_SERVICE_MANAGER="com.amazon.android.hardware.input.AmazonInputManager"  namespace ="AmazonInputManager"

D/VendorConfHelper(  214): Properties $VENDOR_SERVICE_MANAGER="null"  namespace ="AmazonLibrary"

D/VendorConfHelper(  214): Properties $VENDOR_SERVICE_MANAGER="com.amazon.android.internal.view.AmazonWindowManagerImpl"  namespace ="AmazonWindowManager"

D/VendorConfHelper(  214): Properties $VENDOR_SERVICE_MANAGER="com.amazon.android.chronos.ChronosManager"  namespace ="Chronos"

D/VendorConfHelper(  214): Properties $VENDOR_SERVICE_MANAGER="com.amazon.android.app.ContentSupportManager"  namespace ="ContentSupportManager"

D/VendorConfHelper(  214): Properties $VENDOR_SERVICE_MANAGER="null"  namespace ="DeviceInfo"

D/VendorConfHelper(  214): Properties $VENDOR_SERVICE_MANAGER="null"  namespace ="IDME"

D/VendorConfHelper(  214): Properties $VENDOR_SERVICE_MANAGER="com.amazon.nitro.ink.NitroManager"  namespace ="Nitro"

D/VendorConfHelper(  214): Properties $VENDOR_SERVICE_MANAGER="null"  namespace ="SearchManager"

D/VendorConfHelper(  214): Properties $VENDOR_SERVICE_MANAGER="com.amazon.android.softkey.SoftkeyBarManager"  namespace ="SoftkeyBar"

D/VendorConfHelper(  214): Properties $VENDOR_SERVICE_MANAGER="null"  namespace ="TimeService"

D/VendorConfHelper(  214): Properties $VENDOR_SERVICE_MANAGER="null"  namespace ="FileLinker"

D/VendorConfHelper(  214): Properties $VENDOR_SERVICE_MANAGER="null"  namespace ="AmazonActivityManager"

D/VendorConfHelper(  214): Properties $VENDOR_SERVICE_MANAGER="null"  namespace ="SmartSuspend"

D/VendorConfHelper(  214): Properties $VENDOR_SERVICE_MANAGER="com.amazon.android.marketplace.MarketplaceServiceManager"  namespace ="Marketplace"

D/VendorConfHelper(  214): Properties $VENDOR_SERVICE_MANAGER="amazon.app.AmazonKeyguardManager"  namespace ="AmazonKeyguardManager"

I/SystemServer(  574): Entered the Android system server!

D/VendorConfHelper(  574): Properties $VENDOR_SERVICE="com.amazon.android.service.pm.AmazonPackageManagerService"  namespace ="AmazonPackageManager"

D/VendorConfHelper(  574): Properties $VENDOR_SERVICE="com.amazon.android.service.AmazonWifiService"  namespace ="AmazonWifiManager"

D/VendorConfHelper(  574): Properties $VENDOR_SERVICE="com.amazon.android.crl.CRLSetManagerService"  namespace ="CRLSetManager"

D/VendorConfHelper(  574): Properties $VENDOR_SERVICE="null"  namespace ="AmazonDownloadManager"

D/VendorConfHelper(  574): Properties $VENDOR_SERVICE="com.amazon.android.internal.server.input.AmazonInputManagerService"  namespace ="AmazonInputManager"

D/VendorConfHelper(  574): Properties $VENDOR_SERVICE="com.amazon.android.internal.library.AmazonLibraryService"  namespace ="AmazonLibrary"

D/VendorConfHelper(  574): Properties $VENDOR_SERVICE="null"  namespace ="AmazonWindowManager"

D/VendorConfHelper(  574): Properties $VENDOR_SERVICE="com.amazon.android.service.ChronosService"  namespace ="Chronos"

D/VendorConfHelper(  574): Properties $VENDOR_SERVICE="null"  namespace ="ContentSupportManager"

Regards,
Prince

**Comment by prathikshetty** [comment]
Hi ,

Please try below steps.
- adb shell pm uninstall com.github.uiautomator
- adb shell pm uninstall com.github.uiautomator.test
- adb install app-uiautomator.apk
- adb install app-uiautomator-test.apk
- adb push bundle.jar /data/local/tmp/
- adb push uiautomator-stub.jar /data/local/tmp/

And also try **print d.info** instead of d.info in python code.
Thanks

**Comment by 136313283** [comment]
楼上的办法可行， 谢谢了
