### ISSUE TITLE
NameError: name 'urllib3' is not defined; Version : uiautomator-0.1.32

### ISSUE THREAD

**Issue by SureshKL** [xiaocong/uiautomator#69]
When I try to install getting the below Error. Have anybody faced the same issue?
# Version : uiautomator-0.1.32

C:\Users\SURESH\Downloads\New folder\dist\uiautomator-0.1.32>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    import uiautomator
  File "C:\Users\SURESH\Downloads\New folder\dist\uiautomator-0.1.32\uiautomator__init__.py", line 88, in <module>
    class JsonRPCMethod(object):
  File "C:\Users\SURESH\Downloads\New folder\dist\uiautomator-0.1.32\uiautomator__init__.py", line 91, in JsonRPCMethod
    pool = urllib3.PoolManager()
# NameError: name 'urllib3' is not defined

**Comment by kotlinski** [comment]
thx @thlengane, :+1:
